Enable the derive feature when testing
Otherwise ‘cargo test --all-features’ enables it anyway and breaks
with “error[E0252]: the name `Trace` is defined multiple times”.

Signed-off-by: Anders Kaseorg <andersk@mit.edu>